### ISSUE TITLE
APP NAME NEEDED

### ISSUE THREAD

**Issue by cpr5855** [ShootProof/php-sdk#12]
Where do we set the APP NAME. Is this something that is set outside the API?

When I use the php-sdk to authorize it directs me to https://auth.shootproof.com/oauth2/login as expected, however the message above the email input is:

"Authorize APP NAME NEEDED to access your ShootProof account?"

![image](https://cloud.githubusercontent.com/assets/18522529/24823372/b5e41ce2-1bcb-11e7-967b-0ec988fc9388.png)

If I authorize log into the Studio Account and check Integrations/Authorized Apps, it shows "APP NAME NEEDED" along with the various other apps (17hats, ShootProof Desktop Uploader, Shootproof Lightroom Publish Service). 

![image](https://cloud.githubusercontent.com/assets/18522529/24823381/ccf72a64-1bcb-11e7-966f-f2ad4754ad9e.png)

Thanks in advance!

**Comment by rswarthout** [comment]
You will need to write into support@shootproof.com, provide your App ID and the name you would like it set to.

**Comment by cpr5855** [comment]
Ok, good to know. I figured I was just missing something obvious. 

Thank you!
