### ISSUE TITLE
sp.album.get_photos API don't work

### ISSUE THREAD

**Issue by phpstudyone** [ShootProof/php-sdk#13]
[sp.album.get_photos](https://developer.shootproof.com/apidocs#sp.album.get_photos) API return's data : `original` field is error.

![image](https://user-images.githubusercontent.com/11455285/38070782-3ad836b2-3350-11e8-8e62-13d011e0bc0e.png)

![image](https://user-images.githubusercontent.com/11455285/38070757-1a7fe2f2-3350-11e8-89de-657dea691a2d.png)

**Comment by ramsey** [comment]
The original URL returned is a signed URL that is valid for only one hour after it is created. Is it possible you are trying to load the URL after it has expired?

**Comment by phpstudyone** [comment]
Thanks, Ramsey for the reply.

But I found that it is invalid when I upload it on Shootproof and try it immediately.

**Comment by ramsey** [comment]
Thanks for the report. I’ll look into it.

**Comment by phpstudyone** [comment]
@ramsey  do you have any news about this issue?

**Comment by ramsey** [comment]
Can you share some example code? I am unable to reproduce this. I’d like to see how you’re making the `sp.albums.get_photos` request, as well as how you’re making the request to get the original photo.

Thanks!
